Gitignore für node_modules erweitern
emanuelbuholzer/DFMoco2UR pull request #3
Opened 2020-10-29 13:25 UTC by sQoooop

2020-10-30 08:07 UTC, emanuelbuholzer requested changes

2020-10-30 08:07 UTC, emanuelbuholzer commented on dfmoco2ur-ui/src/components/LoggerFilter.js
> +            <Checkbox checked={dense} onChange={(event) => setDense(event.target.checked)} />
Anstatt Checkbox würde ich Chips verwenden: https://material-ui.com/components/chips/#chip-2

Chip outlined wenn inaktiv, ansonsten aktiv.

2020-10-30 08:07 UTC, emanuelbuholzer commented on dfmoco2ur-ui/src/components/LoggerFilter.js
> +  const [dense, setDense] = React.useState(false);
Ich würde nicht einen Boolean als State verwenden. Sondern z.B.
```suggestion
  const [activeFilters, setActiveFilters] = React.useState({Critical: true, Error: true, Warning: true, Info: false, Debug: false});
```
Dann musst du halt immer das ganze Objekt updaten. Vielleicht funktioniert eines der beiden zum dann einen Wert zu aktualisieren:
```js
setActiveFilters({...activeFilters, Info: true});

setActiveFilters(Object.assign(activeFilters, {Info: true});

2020-10-30 08:18 UTC, emanuelbuholzer commented
Tests müssen noch gefixt werden.

2020-11-11 07:31 UTC, sQoooop commented on dfmoco2ur-ui/src/components/LoggView.js
> +      <LoggerFilter></LoggerFilter>
Sorry welche komponente in welcher jetzt? Loggerfilter in Loggerview?

2020-11-11 10:57 UTC, sQoooop commented on dfmoco2ur-ui/src/components/LoggView.js
> +      <LoggerFilter></LoggerFilter>
Habe jetzt folgende struktur: 
- Das grid erhält eine Loggview
- Die Loggview hält Loggfilter und LogMessages
- LogMessages enthält eine Table welche die Messages von Loggentry enthält.

2020-11-11 10:58 UTC, sQoooop commented on dfmoco2ur-ui/src/components/LoggView.js
> +function generate(element) {
Offenbar nicht, gelöscht.

2020-11-11 10:58 UTC, sQoooop commented on dfmoco2ur-ui/src/components/LoggView.js
> +      <LoggerMessages></LoggerMessages>
Bin ich dran

2020-11-12 08:58 UTC, emanuelbuholzer requested changes

2020-11-12 08:58 UTC, emanuelbuholzer commented on dfmoco2ur-ui/src/components/LoggEntry.js
> +
Zeile entfernen. Ich würde sonst noch die Datei in `LogEntry.js` umbennen.

2020-11-12 08:58 UTC, emanuelbuholzer commented on dfmoco2ur-ui/src/components/LoggEntry.js
> +  export default function ControlGrid() {
Komponente entsprechend dem Dateinamen benennen.

```suggestion
  export default function LogEntry() {
```

2020-11-12 08:58 UTC, emanuelbuholzer commented on dfmoco2ur-ui/src/components/LoggEntry.js
> +          <div level="X" timestamp="xxx" message="adaaaa">tüdelüüüü</div>
Ein `div` hat keine Attributte `level`, `timestamp` und `message`. Du kannst in dieser Komponente mit [Props](https://reactjs.org/docs/components-and-props.html) arbeiten, um `level`, `timestamp` und `message` als Variable zu erhalten. Damit kannst du diese Variablen z.B. in mehreren `div` in dieser Komponente darstellen. 

Somit könnte man dann die Komponente wie folgt einbinden:
```jsx
<LogEntry level=20 timestamp={new Date()} message="Irgendwas" />
```

2020-11-12 08:58 UTC, emanuelbuholzer commented on dfmoco2ur-ui/src/components/LoggView.js
> +import React from 'react';
Datei in `LogView` umbenennen.

2020-11-12 08:58 UTC, emanuelbuholzer commented on dfmoco2ur-ui/src/components/LoggView.js
> +  export default function Loggview(){
Komponente entsprechend Dateinamen umbennen: `LogView`.

2020-11-12 08:58 UTC, emanuelbuholzer commented on dfmoco2ur-ui/src/components/LoggerFilter.js
> +function generate(element) {
Entfernen?

2020-11-12 08:58 UTC, emanuelbuholzer commented on dfmoco2ur-ui/src/components/LoggerFilter.js
> +  demo: {
Entfernen? Title auch?

2020-11-12 08:58 UTC, emanuelbuholzer commented on dfmoco2ur-ui/src/components/LoggerFilter.js
> +  const [secondary, setSecondary] = React.useState(false);
Warum brauchst du diesen?

2020-11-12 08:58 UTC, emanuelbuholzer commented on dfmoco2ur-ui/src/components/LoggView.js
> +      <LoggerFilter></LoggerFilter>
Die Logik der `LogFilter` Komponente in dieser Komponente abbilden und `LogMessages` auch, damit der aktuelle Filter gleich auf alle `LogEntry` hier angewendet werden kann.

2020-11-13 08:41 UTC, emanuelbuholzer commented
Könntest du die Table noch mit dem Attribut `size="small"` dense machen?

2021-01-14 14:24 UTC, merged